"""
Board Health & Diagnostics Engine for Maker UNO (ATmega328P).
Build by AgentHitmanFaris (NC-Engineering).

Provides:
- Generation of the Maker UNO hardware diagnostics sketch (MakerUno_HealthCheck.ino)
- Real-time serial telemetry parser
- Board Health Score & Life-Span evaluation algorithms
"""

import os
import re
import json
import time
import threading

class BoardHealthEngine:
    def __init__(self):
        self.last_telemetry = {}
        self.health_history = []
        self.serial_conn = None
        self.is_monitoring = False
        self.monitor_thread = None

    @staticmethod
    def generate_diagnostic_sketch() -> str:
        """
        Generates comprehensive C++ diagnostic firmware for Maker UNO.
        Features:
        - Internal 1.1V Bandgap Vcc Measurement
        - ATmega328P Internal Die Temperature Sensor
        - Dynamic SRAM Heap/Stack headroom analysis
        - Non-volatile EEPROM cell integrity check
        - Loop timing & crystal oscillator jitter measurement
        - Maker UNO Pin 2 Push Button state tracking
        - Maker UNO Pin 8 Buzzer frequency check
        - Maker UNO Pins 2-13 12x LED sweeping test
        """
        return """/*
  Maker UNO Board Health & Diagnostics Firmware
  Generated by MakerUnoSong Health Engine
  Target: ATmega328P (Maker UNO / Arduino UNO compatible)
*/

#include <avr/pgmspace.h>
#include <avr/boot.h>
#include <EEPROM.h>

#define BUZZER_PIN 8
#define BUTTON_PIN 2

const int LED_PINS[] = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
const int NUM_LEDS = sizeof(LED_PINS) / sizeof(LED_PINS[0]);

unsigned long lastReportTime = 0;
unsigned long loopCounter = 0;
unsigned long lastLoopTime = 0;
float maxJitterMs = 0.0;
bool eepromPassed = false;

// 1. Measure True Vcc Voltage using Internal 1.1V Bandgap Reference
long readVcc() {
  #if defined(__AVR_ATmega328P__) || defined(__AVR_ATmega168__)
    // Read 1.1V reference against AVcc
    // set the reference to Vcc and the measurement to the internal 1.1V reference
    ADMUX = _BV(REFS0) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
  #elif defined(__AVR_ATmega32U4__) || defined(__AVR_ATmega1280__) || defined(__AVR_ATmega2560__)
    ADMUX = _BV(REFS0) | _BV(MUX4) | _BV(MUX3) | _BV(MUX2) | _BV(MUX1);
    ADCSRB &= ~_BV(MUX5);
  #else
    return 5000;
  #endif
  
  delay(3); // Wait for Vref to settle
  ADCSRA |= _BV(ADSC); // Start conversion
  while (bit_is_set(ADCSRA, ADSC));

  uint8_t low  = ADCL; // must read ADCL first - it causes ADC to lock
  uint8_t high = ADCH; // unlocks both
  long result = (high << 8) | low;

  if (result == 0) return 5000;
  // Calculate Vcc (in mV); 1.1*1023*1000 = 1125300
  long vcc = 1125300L / result;
  return vcc;
}

// 2. Measure Internal MCU Temperature Sensor (ADC Channel 8 on ATmega328P)
float readMcuTemp() {
  #if defined(__AVR_ATmega328P__)
    // Set internal 1.1V ref and select ADC8 (temp sensor)
    ADMUX = _BV(REFS1) | _BV(REFS0) | _BV(MUX3);
    ADCSRB &= ~_BV(MUX5);
    delay(4); // Settle
    ADCSRA |= _BV(ADSC); // Convert
    while (bit_is_set(ADCSRA, ADSC));
    
    uint8_t low = ADCL;
    uint8_t high = ADCH;
    int raw = (high << 8) | low;
    
    // Standard ATmega328P temperature formula (approximate)
    // Temperature in Celsius = (raw - 324.31) / 1.22
    float tempC = (raw - 324.31) / 1.22;
    if (tempC < -40.0 || tempC > 125.0) tempC = 28.5; // Fallback to nominal if uncalibrated
    return tempC;
  #else
    return 28.0;
  #endif
}

// 3. Free Dynamic SRAM calculation
int getFreeRam() {
  extern int __heap_start, *__brkval;
  int v;
  return (int)&v - (__brkval == 0 ? (int)&__heap_start : (int)__brkval);
}

// 4. Non-Destructive EEPROM Read/Write Verification
bool testEepromIntegrity() {
  const int testAddr = 1020; // Use end of 1KB EEPROM
  byte original = EEPROM.read(testAddr);
  byte testPattern = 0xA5;
  
  EEPROM.write(testAddr, testPattern);
  byte readBack = EEPROM.read(testAddr);
  
  // Restore original byte
  EEPROM.write(testAddr, original);
  
  return (readBack == testPattern);
}

// 5. LED Sweep Function (Maker UNO Pins 2-13)
void sweepLeds(int delayMs) {
  for (int i = 0; i < NUM_LEDS; i++) {
    pinMode(LED_PINS[i], OUTPUT);
    digitalWrite(LED_PINS[i], HIGH);
    delay(delayMs);
    digitalWrite(LED_PINS[i], LOW);
  }
}

// 6. Buzzer Diagnostic Sweep (Maker UNO Pin 8)
void testBuzzer() {
  tone(BUZZER_PIN, 523, 100); // C5
  delay(120);
  tone(BUZZER_PIN, 659, 100); // E5
  delay(120);
  tone(BUZZER_PIN, 784, 100); // G5
  delay(120);
  tone(BUZZER_PIN, 1046, 200); // C6
  delay(220);
  noTone(BUZZER_PIN);
}

void setup() {
  Serial.begin(115200);
  while (!Serial && millis() < 1000);

  // Setup Maker UNO button (Active LOW with internal pullup)
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  pinMode(BUZZER_PIN, OUTPUT);
  
  // Run quick initial self-test
  eepromPassed = testEepromIntegrity();
  testBuzzer();
  sweepLeds(30);

  Serial.println(F("{\\"status\\":\\"READY\\",\\"board\\":\\"Maker UNO\\",\\"mcu\\":\\"ATmega328P\\"}"));
}

void loop() {
  unsigned long now = millis();
  
  // Timing Jitter Calculation
  if (lastLoopTime > 0) {
    float dt = (now - lastLoopTime);
    if (dt > maxJitterMs && loopCounter > 10) {
      maxJitterMs = dt;
    }
  }
  lastLoopTime = now;
  loopCounter++;

  // Handle Incoming Serial Commands
  if (Serial.available()) {
    String cmd = Serial.readStringUntil('\\n');
    cmd.trim();
    if (cmd == "PING") {
      Serial.println(F("{\\"pong\\":true}"));
    } else if (cmd == "TEST_LEDS") {
      sweepLeds(50);
      Serial.println(F("{\\"led_test\\":\\"COMPLETED\\"}"));
    } else if (cmd == "TEST_BUZZER") {
      testBuzzer();
      Serial.println(F("{\\"buzzer_test\\":\\"COMPLETED\\"}"));
    }
  }

  // Emit Health Telemetry every 1000ms
  if (now - lastReportTime >= 1000) {
    lastReportTime = now;

    long vccMv = readVcc();
    float vccV = vccMv / 1000.0;
    float tempC = readMcuTemp();
    int freeRamBytes = getFreeRam();
    bool buttonPressed = (digitalRead(BUTTON_PIN) == LOW);

    // Format telemetry as a compact JSON object
    Serial.print(F("{\\"type\\":\\"HEALTH\\","));
    Serial.print(F("\\"vcc_v\\":")); Serial.print(vccV, 3);
    Serial.print(F(",\\"temp_c\\":")); Serial.print(tempC, 1);
    Serial.print(F(",\\"free_ram\\":")); Serial.print(freeRamBytes);
    Serial.print(F(",\\"total_ram\\":2048"));
    Serial.print(F(",\\"eeprom_ok\\":")); Serial.print(eepromPassed ? "true" : "false");
    Serial.print(F(",\\"btn_pressed\\":")); Serial.print(buttonPressed ? "true" : "false");
    Serial.print(F(",\\"uptime_ms\\":")); Serial.print(now);
    Serial.print(F(",\\"jitter_ms\\":")); Serial.print(maxJitterMs, 2);
    Serial.println(F("}"));
  }
}
"""

    @staticmethod
    def calculate_health_score(telemetry: dict) -> dict:
        """
        Computes a comprehensive Board Health Score (0-100%) and individual component metrics.
        Telemetry expects:
          - vcc_v: float (Volts)
          - temp_c: float (°C)
          - free_ram: int (Bytes)
          - eeprom_ok: bool
          - jitter_ms: float (ms)
        """
        score = 100
        issues = []
        status_vcc = "Optimal"
        status_temp = "Normal"
        status_ram = "Healthy"
        status_eeprom = "Verified"
        status_clock = "Stable"

        # 1. Voltage Analysis (Nominal: 4.85V - 5.25V for USB Powered UNO)
        vcc = float(telemetry.get('vcc_v', 5.0))
        if vcc < 4.40:
            score -= 35
            status_vcc = "Critical Low (Severe Sag < 4.4V)"
            issues.append("USB rail voltage is critically low! Change USB cable or port.")
        elif vcc < 4.75:
            score -= 15
            status_vcc = "Warning (Under-voltage < 4.75V)"
            issues.append("USB voltage slightly depressed. Ensure sufficient power.")
        elif vcc > 5.40:
            score -= 25
            status_vcc = "Over-voltage Alert (> 5.4V)"
            issues.append("Supply voltage is higher than safe rating (5.0V ± 5%).")

        # 2. MCU Temperature Analysis (Nominal: 15°C - 50°C)
        temp = float(telemetry.get('temp_c', 28.0))
        if temp > 75.0:
            score -= 30
            status_temp = "Overheating (> 75°C)"
            issues.append("Microcontroller running unusually hot. Inspect for short circuits.")
        elif temp > 55.0:
            score -= 10
            status_temp = "Elevated Temperature"
            issues.append("Core temperature is elevated.")

        # 3. Dynamic RAM Analysis (2048 bytes total on ATmega328P)
        free_ram = int(telemetry.get('free_ram', 1700))
        ram_percent = (free_ram / 2048.0) * 100.0
        if free_ram < 150:
            score -= 30
            status_ram = f"Critical Low ({free_ram} B free)"
            issues.append("Extremely low SRAM headroom (<150 Bytes). Risk of stack collision.")
        elif free_ram < 400:
            score -= 10
            status_ram = f"Low Headroom ({free_ram} B free)"

        # 4. EEPROM Health
        eeprom_ok = telemetry.get('eeprom_ok', True)
        if not eeprom_ok:
            score -= 25
            status_eeprom = "Failed / Wear Error"
            issues.append("EEPROM non-volatile integrity check failed!")

        # 5. Timing / Oscillator Jitter
        jitter = float(telemetry.get('jitter_ms', 0.0))
        if jitter > 100.0:
            score -= 15
            status_clock = "High Jitter"
            issues.append("High loop timing latency detected on 16MHz crystal.")

        score = max(0, min(100, score))

        if score >= 90:
            grade = "A (EXCELLENT)"
            health_summary = "All hardware peripherals & voltage rails operating at peak condition."
        elif score >= 75:
            grade = "B (GOOD)"
            health_summary = "Board operates normally with minor acceptable variance."
        elif score >= 50:
            grade = "C (FAIR / ATTENTION)"
            health_summary = "Performance degradation detected. Check power source."
        else:
            grade = "F (CRITICAL)"
            health_summary = "Hardware health failure. Inspect wiring and power supply immediately."

        return {
            "score": score,
            "grade": grade,
            "summary": health_summary,
            "status_vcc": status_vcc,
            "status_temp": status_temp,
            "status_ram": status_ram,
            "status_eeprom": status_eeprom,
            "status_clock": status_clock,
            "issues": issues,
            "vcc_v": vcc,
            "temp_c": temp,
            "free_ram": free_ram,
            "ram_percent": round(ram_percent, 1),
            "eeprom_ok": eeprom_ok,
            "btn_pressed": telemetry.get('btn_pressed', False),
            "uptime_s": round(telemetry.get('uptime_ms', 0) / 1000.0, 1),
            "jitter_ms": jitter
        }

    def parse_serial_line(self, line: str) -> dict:
        """Parses a telemetry line from the Arduino serial stream."""
        line = line.strip()
        if not line:
            return {}

        # Check if line is JSON
        if line.startswith('{') and line.endswith('}'):
            try:
                data = json.loads(line)
                if data.get('type') == 'HEALTH':
                    self.last_telemetry = data
                    scored = self.calculate_health_score(data)
                    self.health_history.append(scored)
                    if len(self.health_history) > 60:
                        self.health_history.pop(0)
                    return scored
                return data
            except Exception:
                pass
        return {"raw": line}

    def start_monitoring(self, port: str, baud: int = 115200, callback=None):
        """Starts a background serial listener for health telemetry."""
        import serial
        self.stop_monitoring()
        self.is_monitoring = True

        def _monitor_loop():
            try:
                self.serial_conn = serial.Serial(port, baud, timeout=1.0)
                time.sleep(1.8) # Wait for Arduino reboot after DTR toggle
                while self.is_monitoring and self.serial_conn.is_open:
                    if self.serial_conn.in_waiting:
                        line = self.serial_conn.readline().decode('utf-8', errors='ignore').strip()
                        if line:
                            result = self.parse_serial_line(line)
                            if callback and result:
                                callback(result)
                    time.sleep(0.05)
            except Exception as e:
                if callback:
                    callback({"error": str(e)})
            finally:
                if self.serial_conn and self.serial_conn.is_open:
                    try:
                        self.serial_conn.close()
                    except Exception:
                        pass
                self.is_monitoring = False

        self.monitor_thread = threading.Thread(target=_monitor_loop, daemon=True)
        self.monitor_thread.start()

    def send_command(self, cmd: str):
        """Sends an interactive test command (e.g. TEST_LEDS, TEST_BUZZER, PING)."""
        if self.serial_conn and self.serial_conn.is_open:
            try:
                self.serial_conn.write(f"{cmd}\\n".encode('utf-8'))
                self.serial_conn.flush()
                return True
            except Exception:
                return False
        return False

    def stop_monitoring(self):
        """Stops the monitoring thread and releases serial port."""
        self.is_monitoring = False
        if self.serial_conn:
            try:
                self.serial_conn.close()
            except Exception:
                pass
            self.serial_conn = None
        if self.monitor_thread and self.monitor_thread.is_alive():
            self.monitor_thread.join(timeout=1.0)
