import mido
import math

class MidiConverter:
    def __init__(self):
        # notes is a list of dictionaries: {'start': ms, 'duration': ms, 'pitch': midi_note_number}
        self.notes = []
        self.total_duration = 0

    def note_to_freq(self, note):
        if note is None or note == 0:
            return 0
        return int(440 * (2 ** ((note - 69) / 12)))

    def load_midi(self, filepath):
        """
        Loads a MIDI file and converts it into a monophonic list of note events.
        Prioritizes the highest note if multiple are playing at once (simple monophonic conversion).
        """
        mid = mido.MidiFile(filepath)
        self.notes = []

        # Iterate the MidiFile object directly.
        # This yields messages with 'time' converted to seconds (delta time).
        # Re-read using the play-like iterator for time conversion convenience,
        # but we iterate the messages to build our structure

        # To handle this properly with editing in mind, we want "Note objects"
        # Since the output is monophonic, let's keep it simple.

        # New approach:
        # 1. Iterate all messages, tracking absolute time.
        # 2. Keep track of all active notes.
        # 3. Create a list of "Segments" or "Notes".

        # Actually, the original script's logic was "State Machine" style.
        # For a Piano Roll editor, we want distinct Note objects.

        temp_notes = []
        active_starts = {} # pitch -> start_time_ms

        abs_time_ms = 0.0

        for msg in mid:
            dt_ms = msg.time * 1000
            abs_time_ms += dt_ms

            if msg.type == 'note_on' and msg.velocity > 0:
                if msg.note not in active_starts:
                    active_starts[msg.note] = abs_time_ms

            elif msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
                if msg.note in active_starts:
                    start_t = active_starts.pop(msg.note)
                    duration = abs_time_ms - start_t
                    if duration > 0:
                        temp_notes.append({
                            'start': int(start_t),
                            'duration': int(duration),
                            'pitch': msg.note
                        })

        self.notes = sorted(temp_notes, key=lambda x: x['start'])
        self.update_duration()

    def update_duration(self):
        if not self.notes:
            self.total_duration = 0
        else:
            self.total_duration = max(n['start'] + n['duration'] for n in self.notes)

    def get_notes(self):
        return self.notes

    def set_notes(self, notes):
        self.notes = sorted(notes, key=lambda x: x['start'])
        self.update_duration()

    def export_arduino(self, output_filepath):
        """
        Generates the Arduino code.
        Converts the overlapping/gap-filled note list into a continuous stream of (freq, duration).
        """

        # Flatten logic:
        # We need to turn the list of notes into a sequence of tone/silence segments.
        # Strategy: Iterate through time.

        # Create events: (time, type, pitch)
        # type: 1 for start, -1 for end

        events = []
        for n in self.notes:
            events.append((n['start'], 1, n['pitch']))
            events.append((n['start'] + n['duration'], -1, n['pitch']))

        events.sort(key=lambda x: (x[0], x[1])) # Sort by time, then type (end before start to avoid zero overlaps?)
        # Actually start (1) before end (-1)? No, if one ends and another starts at same time.

        segments = []
        current_time = 0
        active_pitches = [] # List of pitches currently on

        for time, type, pitch in events:
            duration = time - current_time

            if duration > 0:
                # Determine what was playing during this interval
                if active_pitches:
                    # Monophonic: play the last added note (or highest?)
                    # Let's play the highest pitch usually, or the most recent.
                    # Standard synth mono mode is often 'last note priority'.
                    # Let's do Last Note Priority.
                    playing_pitch = active_pitches[-1]
                    segments.append((self.note_to_freq(playing_pitch), int(duration)))
                else:
                    # Silence
                    segments.append((0, int(duration)))

            current_time = time

            if type == 1:
                active_pitches.append(pitch)
            else:
                if pitch in active_pitches:
                    active_pitches.remove(pitch) # Removes first occurrence

        # Generate Code
        header = """/*
  Maker UNO Melody
  Generated by Portable MIDI to Arduino Converter
*/

#define BUZZER_PIN 8

"""
        melody_array = "int melody[] = {\n"
        duration_array = "int noteDurations[] = {\n"

        count = 0
        note_count = 0
        for freq, duration in segments:
            if duration <= 0: continue

            melody_array += f"  {freq}, "
            duration_array += f"  {duration}, "
            count += 1
            note_count += 1
            if count % 10 == 0:
                melody_array += "\n"
                duration_array += "\n"

        melody_array = melody_array.rstrip(", \n") + "\n};\n"
        duration_array = duration_array.rstrip(", \n") + "\n};\n"

        setup_loop = f"""
int noteCount = {note_count};

void setup() {{
  pinMode(BUZZER_PIN, OUTPUT);
}}

void loop() {{
  for (int i = 0; i < noteCount; i++) {{
    int duration = noteDurations[i];
    if (melody[i] > 0) {{
      tone(BUZZER_PIN, melody[i], duration);
    }} else {{
      noTone(BUZZER_PIN);
    }}
    delay(duration);
    noTone(BUZZER_PIN);
  }}
  delay(2000); // Wait 2 seconds before repeating
}}
"""
        full_code = header + melody_array + "\n" + duration_array + "\n" + setup_loop

        with open(output_filepath, 'w') as f:
            f.write(full_code)

        return True
