import mido
import functools
import argparse
import os

@functools.lru_cache(maxsize=128)
def note_to_freq(note):
    return int(440 * (2 ** ((note - 69) / 12)))

def sanitize_cpp_comment(text):
    """Sanitize input to prevent C++ block comment injection."""
    return str(text).replace("*/", "* /")

def main():
    parser = argparse.ArgumentParser(description='Convert MIDI to Arduino code for Maker UNO')
    parser.add_argument('input_file', help='Path to input MIDI file')
    parser.add_argument('output_file', help='Path to output .ino file')
    args = parser.parse_args()

    mid = mido.MidiFile(args.input_file)
    bpm = 120
    time_signature = "4/4"
    key_signature = "C"
    song_name = os.path.basename(args.input_file)
    artist = "Unknown"

    # Extract Meta info first
    for track in mid.tracks:
        for msg in track:
            if msg.type == 'set_tempo':
                bpm = round(mido.tempo2bpm(msg.tempo))
            elif msg.type == 'time_signature':
                time_signature = f"{msg.numerator}/{msg.denominator}"
            elif msg.type == 'key_signature':
                key_signature = msg.key
            elif msg.type == 'track_name':
                if song_name.endswith('.mid') or song_name.endswith('.midi'):
                    song_name = msg.name
            elif msg.type == 'text' and "artist" in msg.text.lower():
                artist = msg.text
            elif msg.type == 'copyright' and artist == "Unknown":
                artist = msg.text


    notes_output = [] # (frequency, duration_ms)
    active_pitches = []

    arp_time_ms = 90
    arp_index = 0

    for msg in mid:
        dt = msg.time # in seconds
        if dt > 0:
            duration_ms = int(dt * 1000)
            if duration_ms > 0:
                if active_pitches:
                    sorted_pitches = sorted(active_pitches)
                    if len(sorted_pitches) == 1:
                        notes_output.append((note_to_freq(sorted_pitches[0]), duration_ms))
                    else:
                        highest_pitch = sorted_pitches[-1]
                        lowest_pitch = sorted_pitches[0]
                        rem_dur = duration_ms
                        while rem_dur > 0:
                            if arp_index % 2 == 0:
                                step_dur = min(60, rem_dur)
                                notes_output.append((note_to_freq(highest_pitch), step_dur))
                            else:
                                step_dur = min(30, rem_dur)
                                notes_output.append((note_to_freq(lowest_pitch), step_dur))
                            rem_dur -= step_dur
                            arp_index += 1
                else:
                    notes_output.append((0, duration_ms))
                    arp_index = 0

        if msg.type == 'note_on' and msg.velocity > 0:
            active_pitches.append(msg.note)
        elif msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
            if msg.note in active_pitches:
                active_pitches.remove(msg.note)

    # Generate Arduino Code
    header = f"""/*
  Maker UNO Melody
  Generated by Portable MIDI to Arduino Converter
  Build by AgentHitmanFaris (NC-Engineering)
  Detected Info -> BPM: {sanitize_cpp_comment(bpm)} | Time Sig: {sanitize_cpp_comment(time_signature)} | Key: {sanitize_cpp_comment(key_signature)}
  Song Name: {sanitize_cpp_comment(song_name)}
  Artist: {sanitize_cpp_comment(artist)}
*/

#include <avr/pgmspace.h>

#define BUZZER_PIN 8

"""

    melody_array = "const int melody[] PROGMEM = {\n"
    duration_array = "const int noteDurations[] PROGMEM = {\n"

    # Memory Optimization: Merge adjacent segments with identical frequencies (especially adjacent rests)
    optimized_notes = []
    for freq, duration in notes_output:
        if duration <= 0: continue
        if optimized_notes and optimized_notes[-1][0] == freq:
            optimized_notes[-1] = (freq, optimized_notes[-1][1] + duration)
        else:
            optimized_notes.append((freq, duration))

    melody_rows = []
    duration_rows = []
    for i in range(0, len(optimized_notes), 10):
        chunk = optimized_notes[i : i + 10]
        melody_rows.append("  " + ", ".join(str(f) for f, d in chunk))
        duration_rows.append("  " + ", ".join(str(d) for f, d in chunk))

    melody_array += ",\n".join(melody_rows) + "\n};\n"
    duration_array += ",\n".join(duration_rows) + "\n};\n"

    setup_loop = f"""
// --- TO ADJUST TEMPO: Increase for FASTER, decrease for SLOWER ---
float tempoMultiplier = 1.0;

const int noteCount = sizeof(melody) / sizeof(melody[0]);

void setup() {{
  pinMode(BUZZER_PIN, OUTPUT);
}}

void loop() {{
  for (int i = 0; i < noteCount; i++) {{
    int freq = pgm_read_word_near(melody + i);
    int duration = pgm_read_word_near(noteDurations + i);
    
    // Apply Tempo Multiplier
    int finalDuration = (int)(duration / tempoMultiplier);
    
    if (freq > 0) {{
      // Articulation: Play for 90% of duration, 10% silence
      tone(BUZZER_PIN, freq, finalDuration * 0.9);
    }} else {{
      noTone(BUZZER_PIN);
    }}
    
    delay(finalDuration);
    noTone(BUZZER_PIN);
  }}
  delay(2000); // Wait 2 seconds before repeating
}}
"""

    full_code = header + melody_array + "\n" + duration_array + "\n" + setup_loop

    with open(args.output_file, 'w') as f:
        f.write(full_code)

    print(f"Successfully generated {args.output_file}")

if __name__ == "__main__":
    main()