import mido
import sys
import argparse

def note_to_freq(note):
    return int(440 * (2 ** ((note - 69) / 12)))

def main():
    parser = argparse.ArgumentParser(description='Convert MIDI to Arduino code for Maker UNO')
    parser.add_argument('input_file', help='Path to input MIDI file')
    parser.add_argument('output_file', help='Path to output .ino file')
    args = parser.parse_args()

    mid = mido.MidiFile(args.input_file)

    notes_output = [] # (frequency, duration_ms)

    active_pitches = []

    # Iterate through the MidiFile object directly.
    # This yields messages with 'time' converted to seconds (delta time).

    for msg in mid:
        dt = msg.time # in seconds
        if dt > 0:
            duration_ms = int(dt * 1000)
            if duration_ms > 0:
                freq = 0
                if active_pitches:
                    freq = note_to_freq(active_pitches[-1])
                notes_output.append((freq, duration_ms))

        if msg.type == 'note_on' and msg.velocity > 0:
            active_pitches.append(msg.note)
        elif msg.type == 'note_off' or (msg.type == 'note_on' and msg.velocity == 0):
            if msg.note in active_pitches:
                active_pitches.remove(msg.note)

    # Generate Arduino Code
    header = """/*
  Maker UNO Melody
  Generated by midi_to_arduino.py
*/

#define BUZZER_PIN 8

"""

    melody_array = "int melody[] = {\n"
    duration_array = "int noteDurations[] = {\n"

    count = 0
    for freq, duration in notes_output:
        melody_array += f"  {freq}, "
        duration_array += f"  {duration}, "
        count += 1
        if count % 10 == 0:
            melody_array += "\n"
            duration_array += "\n"

    melody_array = melody_array.rstrip(", \n") + "\n};\n"
    duration_array = duration_array.rstrip(", \n") + "\n};\n"

    setup_loop = f"""
int noteCount = {len(notes_output)};

void setup() {{
  pinMode(BUZZER_PIN, OUTPUT);
}}

void loop() {{
  for (int i = 0; i < noteCount; i++) {{
    int duration = noteDurations[i];
    if (melody[i] > 0) {{
      tone(BUZZER_PIN, melody[i], duration);
    }} else {{
      noTone(BUZZER_PIN);
    }}
    delay(duration);
    noTone(BUZZER_PIN);
  }}
  delay(2000); // Wait 2 seconds before repeating
}}
"""

    full_code = header + melody_array + "\n" + duration_array + "\n" + setup_loop

    with open(args.output_file, 'w') as f:
        f.write(full_code)

    print(f"Successfully generated {args.output_file}")

if __name__ == "__main__":
    main()
